name: swarm_cloud
description: Swarm Cloud Flutter SDK.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  swarm_cloud_platform_interface: 0.0.3
  swarm_cloud_web: 0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      # android:
      #   default_package: swarm_cloud_android
      # ios:
      #   default_package: swarm_cloud_ios
      web:
        default_package: swarm_cloud_web
