name: swarm_cloud
description: Swarm Cloud Flutter SDK.
version: 0.3.0
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  swarm_cloud_platform_interface: ^0.3.0
  swarm_cloud_web: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.swarmcloud.sdk
        pluginClass: CdnbyePlugin
      ios:
        pluginClass: CdnbyePlugin
      web:
        default_package: swarm_cloud_web
