name: swarm_cloud_platform_interface
description: A platform_interface of swarm cloud sdk
version: 0.5.0
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  safemap: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0