name: swarm_cloud_web
description: Swarm Cloud SDK web platform.
version: 0.5.0
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SwarmCloudWeb 
        fileName: swarm_cloud_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  swarm_cloud_platform_interface: ^0.5.0
  video_player_web_hls_swarm_cloud: ^0.3.0
  js: ^0.6.3
  safemap: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# dependency_overrides:
#   video_player_web_hls_swarm_cloud:
#     path: ../swarm_cloud_video_player_hls_fork/
#   swarm_cloud_platform_interface:
#     path: ../swarm_cloud_platform_interface/
